#!/bin/bash

echo Content-type: text/html
echo
echo "<pre>"

# removing old files.
rm -f table.g
rm -f rt*
rm -f *.pix
rm -f temp*
rm -f ../../cgi-images/*

#initialising variable for the values filled in the form
#length of the top
xmax=`echo "$QUERY_STRING" | cut -d"&" -f1 | cut -d"=" -f2`
#Breadth of the top
ymax=`echo "$QUERY_STRING" | cut -d"&" -f2 | cut -d"=" -f2`
#thickness of the top
zmax=`echo "$QUERY_STRING" | cut -d"&" -f3 | cut -d"=" -f2`
#length of leg
lxmax=`echo "$QUERY_STRING" | cut -d"&" -f4 | cut -d"=" -f2`
#width of leg
lymax=`echo "$QUERY_STRING" | cut -d"&" -f5 | cut -d"=" -f2`
#height of leg
lzmax=`echo "$QUERY_STRING" | cut -d"&" -f6 | cut -d"=" -f2`
#subtracting to get the x min and ymin of leg
lxmin=`expr $xmax - $lxmax`
lymin=`expr $ymax - $lymax`
#Making the table to be at tehtop of legs
tzmax=`expr $zmax + $lzmax`

echo "Processing your Table:"
#defining various views
front=frontview
side=sideview
top=topview
iso=isoview

#mged commands
cat <<EOF | env /usr/brlcad/bin/mged -c table.g
in tableSurface.s rpp 0 $xmax 0 $ymax $lzmax $tzmax
in leg1.s rpp 0 $lxmax 0 $lymax 0 $lzmax
in leg2.s rpp $lxmin $xmax 0 $lymax 0 $lzmax
in leg3.s rpp 0 $lxmax $lymin $ymax 0 $lzmax
in leg4.s rpp $lxmin $xmax $lymin $ymax 0 $lzmax
r table.r u tableSurface.s u leg1.s u leg2.s u leg3.s u leg4.s
mater table.r plastic 12 164 220 0
B table.r
ae 0 0
saveview $front
ae 270 0
saveview $side
ae -90 90 
saveview $top
ae 30 30
saveview $iso
EOF

# adding "env /usr/brlcad/bin/" in the beginning of 2nd line of raytracing file
# and sending output to temporary file.
sed '2cenv /usr/brlcad/bin/rt -M \\' $front > tempFile1
sed '2cenv /usr/brlcad/bin/rt -M \\' $side > tempFile2
sed '2cenv /usr/brlcad/bin/rt -M \\' $top > tempFile3
sed '2cenv /usr/brlcad/bin/rt -M \\' $iso > tempFile4

# removing original raytracing file.
rm $front
rm $side
rm $top
rm $iso

# changing name of temporary file to that of original file.
mv tempFile1 $front
mv tempFile2 $side
mv tempFile3 $top
mv tempFile4 $iso

# give executable permissions to raytrace file.
chmod 777 $front
chmod 777 $side
chmod 777 $top
chmod 777 $iso

# executing raytrace file. This will produce raw image in .pix tormat and a log
#file.
./$front
./$side
./$top
./$iso

# converting .pix file to png image using BRLCAD commands.
env /usr/brlcad/bin/pix-png < $front.pix > $front.png
env /usr/brlcad/bin/pix-png < $side.pix > $side.png
env /usr/brlcad/bin/pix-png < $top.pix > $top.png
env /usr/brlcad/bin/pix-png < $iso.pix > $iso.png

chmod 777 $front.png
chmod 777 $side.png
chmod 777 $top.png
chmod 777 $iso.png


# copying final image to public_html for displaying on browser.
cp $front.png ../../cgi-images/
cp $side.png ../../cgi-images/
cp $top.png ../../cgi-images/
cp $iso.png ../../cgi-images/
echo "<meta http-equiv="refresh" content="2;url=http://cad.devplace.in/multi_view.html">"
#echo "<a href=\"../../multi_view.html\">Congo! you made a table with different views check em here </a>"
echo "<pre>"
